# Generated by Django 3.2.6 on 2021-08-26 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 17, 22, 54, 390528, tzinfo=utc)),
        ),
    ]
