# Generated by Django 3.2.6 on 2021-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210829_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=128, null=True),
        ),
    ]
