# Generated by Django 3.2.6 on 2021-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210831_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default='2021-09-04'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default='2021-09-04'),
        ),
    ]
